Feature/homepage
iSirThijs/jungle-gym pull request #145
Opened 2021-05-28 13:49 UTC by sreen020

# Description

Closes #120 

Branch name: feature/homepage

## Type of change

Please select the option that is relevant

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

# Checklist

- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] All the required documentation is added.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.

# Additional information

_[Provided extra information if necessary]_

2021-05-28 14:27 UTC, jochemvogel commented
Ik zou `index.vue` vervangen met de code van dit PR, zodat het de homepagina wordt. Dan zou ik een file aan maken `games/index.vue` en daar zou ik de huidige `index.vue` in plakken.

Dan heb je:
1. Een homepagina (dit pull request) die beschikbaar is via `/`
2. Een lijst met alle spellen die beschikbaar is op `/games`. Die pagina bestaat nu nog niet, dus dat is een logische keuze.

Uiteindelijk willen we sowieso `/games` hernoemen naar `/spel` of `/spellen`, maar doe nu nog maar `/games`

2021-05-31 13:23 UTC, jochemvogel approved these changes

2021-05-31 14:58 UTC, iSirThijs commented
Ik gooi hier wel even een commit tegenaan om gelijk /spellen te maken

2021-05-31 15:47 UTC, iSirThijs requested changes

2021-05-31 15:47 UTC, iSirThijs commented on src/lib/GameList/GameListCarousel.svelte
> +				</div>
Hier kan je gewoon de het component `GameListCard` gebruiken. Dit houd de boel een beetje consistent als er een wijziging is in bijvoorbeeld de labels

2021-05-31 15:47 UTC, iSirThijs commented on src/lib/GameList/GameListCarousel.svelte
> +	<h2>{carouselTitle} - {gamesData.length}</h2>
```suggestion
	<h1>{carouselTitle} - {gamesData.length}</h1>
```

`Section` is sectioning content en vanaf dat punt kan je opneiuw beginnen met nummer

2021-05-31 15:47 UTC, iSirThijs commented on src/lib/GameList/GameListCarousel.svelte
> +	<h2>{carouselTitle} - {gamesData.length}</h2>
Dit is dan ook consistent met de `/spellen` overzicht pagina

2021-05-31 15:47 UTC, iSirThijs commented on src/lib/GameList/GameListHighlighted.svelte
> +	<h2>Uitgelichte spellen</h2>
```suggestion
	<h1>Uitgelichte spellen</h1>
```

2021-05-31 15:47 UTC, iSirThijs commented on src/lib/GameList/GameListHighlighted.svelte
> +			</div>
`GameListCard` component gebruiken ?

2021-05-31 15:47 UTC, iSirThijs commented on src/routes/index.svelte
> -	});
Misschien een idee om `onMount` erin te laten en door te sturen naar `/spellen` zodat je de offline spellen ziet:
```ts
import { goto } from '$app/navigation'
onMount(() => {
  if (!navigator.onLine) goto('/spellen')
}
```

2021-06-01 09:16 UTC, iSirThijs approved these changes

2021-06-01 09:16 UTC, iSirThijs commented on src/routes/index.svelte
> +<GameListCarousel gamesData={games} carouselTitle="Favoriete spellen" />
Kun je dit in een `<main>` tag zetten?
```suggestion
<main>
<GameListHighlighted />
<GameListCarousel gamesData={newestGames} carouselTitle="Nieuwe spellen" />
<GameListCarousel gamesData={games} carouselTitle="Favoriete spellen" />
<main>
```

2021-06-01 09:19 UTC, merged