Feature/filter pop up linken aan dropdown buttons
iSirThijs/jungle-gym pull request #63
Opened 2021-05-20 11:05 UTC by RooyyDoe

# Description

Closes #52 

Branch name: `feature/filter-pop-up-linken-aan-dropdown-buttons`

_[Please include a summary of the change and which issue is fixed]_

Wanneer er nu op de filter knop wordt gedrukt komt het filter menu omhoog en kan ook weer weg worden geklikt door op de `cancel` button te klikken.

Please select the option that is relevant

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

# Checklist

- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] All the required documentation is added.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.

# Additional information

_[Provided extra information if necessary]_

2021-05-20 12:45 UTC, jochemvogel reviewed
Ziet er nice uit. Ik moet later nog even uitchecken om te kijken wat het precies doet. Hier wil ik dus die deploy previews voor. Kijk nog ook nog evens naar de warnings die er staan. Zijn bepaalde selectoren die niet gebruikt worden. Lijkt mij dat je deze gewoon kunt verwijderen

2021-05-20 12:45 UTC, jochemvogel commented on src/components/FilterPopUp.svelte
> +	// function selectValue() {
Zijn deze comments nodig?

2021-05-20 12:45 UTC, jochemvogel commented on src/components/FilterPopUp.svelte
> +	console.log('this', submitBtn);
Console log nog even verwijderen. 🙂 Inclusief wat er boven staat. Is dat nodig?

2021-05-20 12:45 UTC, jochemvogel commented on src/components/filter.svelte
> +		<FilterButton filterTitle="Spelsoort" on:click={() => (spelsoorten = !spelsoorten)} />
Hier heb ik het anders gedaan. Ik gebruik [slots](https://github.com/iSirThijs/jungle-gym/blob/development/src/components/Button/ButtonLight.svelte). Maakt niet uit wat we doen. Maar moet wel even consistent zijn. Wat zullen we doen? Meegeven via props of via `<FilterButton>Spelsoort</FilterButton>`. Weet niet wat de best practice is omtrent slots. Kan ook dat dit meer voor pagina templates is. @iSirThijs misschien?

2021-05-20 12:45 UTC, jochemvogel commented on src/components/filter.svelte
> +		font-size: 1rem;
```suggestion
		font-size: 1em;
```

2021-05-20 12:45 UTC, jochemvogel commented on src/components/filter.svelte
> +		padding: 0 1rem;
```suggestion
		padding: 0 1em;
```

2021-05-20 12:45 UTC, jochemvogel commented on src/routes/index.svelte
> +	.red {
Wordt niet gebruikt? Zo zijn er nog een aantal, zoals `.blue`

2021-05-20 14:21 UTC, iSirThijs commented
ik heb geen prettier/lint gedaan om de merge op te lossen

2021-05-21 07:58 UTC, jochemvogel commented on src/components/GameList/GameListFilter.svelte
> +	import FilterPopUp from '$lib/Gamelist/GameListPopUp.svelte';
GameList !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! niet Gamelist

2021-05-21 09:52 UTC, jochemvogel reviewed
Nog wat comments

2021-05-21 09:52 UTC, jochemvogel commented on README.md
> +## test
:netjes:

2021-05-21 09:52 UTC, jochemvogel commented on src/components/GameList/GameListFilter.svelte
> +	import FilterPopUp from '$lib/GameList/GameListPopup.svelte';
Dit moet wel even anders vind ik. Is niet heel consistent

`GameListPopup` wordt `FilterPopUp`. Ben altijd wel voorstander om hetgeen wat je importeert hetzelfde te noemen als hoe je het in het component gebruikt. Nu is `GameListPopup` misschien niet zo'n goede naam, maar weet niet. Misschien dat je het op een andere plek kan zetten, want dit vind ik nogal verwarren.d

2021-05-21 09:52 UTC, jochemvogel commented on src/components/GameList/GameListFilter.svelte
> +{#if spelsoorten}
Wilden we dit in Nederlands doen in de code? @sreen020 @RooyyDoe @iSirThijs

2021-05-21 09:52 UTC, jochemvogel commented on src/components/GameList/GameListFilter.svelte
> +{#if spelsoorten}
Kan hoor. Maar even voor de zekerheid. Zijn variabelen: I know.

2021-05-21 09:52 UTC, jochemvogel commented on src/components/GameList/GameListFilter.svelte
> +		font-size: 1rem;
```suggestion
		font-size: 1em;
```

2021-05-21 09:52 UTC, jochemvogel commented on src/components/GameList/GameListFilter.svelte
> +		padding: 0 1rem;
```suggestion
		padding: 0 1em;
```

2021-05-21 09:52 UTC, jochemvogel commented on src/components/GameList/GameListPopup.svelte
> +<div class="black-overlay" on:click />
Wat doet `on:click` hier?

2021-05-21 09:52 UTC, jochemvogel commented on src/components/GameList/GameListPopup.svelte
> +		padding: 0.7rem 2rem;
```suggestion
		padding: 0.7em 2em;
```

2021-05-21 09:52 UTC, jochemvogel commented on src/routes/__layout.svelte
> +		padding: 2rem 0 1rem;
```suggestion
		padding: 2em 0 1em;
```

2021-05-21 09:52 UTC, jochemvogel commented on src/routes/index.svelte
> +	export async function load({ page }): Promise<unknown> {
`page` wordt nergens gebruikt. Klopt dat?

2021-05-21 09:52 UTC, jochemvogel commented on src/routes/index.svelte
>  	// import GameListCard from '$lib/GameList/GameListCard.svelte';
Comment kan eruit lijkt mij

2021-05-21 09:56 UTC, iSirThijs requested changes

2021-05-21 09:56 UTC, iSirThijs commented on src/components/GameList/GameListFilter.svelte
> +			value: 'reactie'
de values hier kloppen nog niet met `games.d.ts`. Je kan voor value gebruiken: 'tikspel', 'balspel', 'loopspel' en 'reactiespel'

2021-05-21 09:56 UTC, iSirThijs commented on src/components/GameList/GameListFilter.svelte
> +	};
Dit soort test functies moeten eruit...
```suggestion
```

2021-05-21 09:56 UTC, iSirThijs commented on src/components/GameList/GameListFilter.svelte
>  	/>
Gebruik consistent engels of Nederlands. Dus `filterTitle=targetgroup` dan moet groepen ook `targetGroup` zijn etc

2021-05-21 10:27 UTC, iSirThijs approved these changes

2021-05-21 10:29 UTC, merged